### ISSUE TITLE
Uncaught exception in binary message listener

### ISSUE THREAD

**Issue by JankoLancer** [feilfeilundfeil/flutter_in_app_update#18]
I am getting this error when try to update for the second time (first time canceled by user).

```
E/DartMessenger(29295): Uncaught exception in binary message listener
E/DartMessenger(29295): android.content.IntentSender$SendIntentException
E/DartMessenger(29295): 	at android.app.Activity.startIntentSenderForResultInner(Activity.java:5521)
E/DartMessenger(29295): 	at android.app.Activity.startIntentSenderForResult(Activity.java:5489)
E/DartMessenger(29295): 	at com.google.android.play.core.appupdate.d.startIntentSenderForResult(Unknown Source:9)
E/DartMessenger(29295): 	at com.google.android.play.core.appupdate.b.startUpdateFlowForResult(Unknown Source:35)
E/DartMessenger(29295): 	at com.google.android.play.core.appupdate.b.startUpdateFlowForResult(Unknown Source:5)
E/DartMessenger(29295): 	at de.ffuf.in_app_update.InAppUpdatePlugin.performImmediateUpdate(InAppUpdatePlugin.kt:111)
E/DartMessenger(29295): 	at de.ffuf.in_app_update.InAppUpdatePlugin.onMethodCall(InAppUpdatePlugin.kt:42)
E/DartMessenger(29295): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/DartMessenger(29295): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/DartMessenger(29295): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/DartMessenger(29295): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(29295): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/DartMessenger(29295): 	at android.os.Looper.loop(Looper.java:181)
E/DartMessenger(29295): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/DartMessenger(29295): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(29295): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/DartMessenger(29295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (29295): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method performImmediateUpdate on channel in_app_update)
[38;5;244mE/flutter (29295): #0      MethodChannel._invokeMethod[39;49m
E/flutter (29295): <asynchronous suspension>
[38;5;244mE/flutter (29295): #1      MethodChannel.invokeMethod[39;49m
[38;5;248mE/flutter (29295): #2      InAppUpdate.performImmediateUpdate[39;49m

```

**Comment by adityadroid** [comment]
I have the exact same issue. Any solution to this @feilfeilundfeil ?

**Comment by jonasbark** [comment]
Please check version 1.1.8.
