### ISSUE TITLE
App Crashes after update

### ISSUE THREAD

**Issue by neokree** [feilfeilundfeil/flutter_in_app_update#29]
Hello,

I'm using the `1.1.7` version. 
For a very tiny list of devices our app crashes after the user installed the update. 

We were able to tell this because of this Crashlytics stacktrace:
```
Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by android.content.IntentSender$SendIntentException
       at android.app.Activity.startIntentSenderForResultInner(Activity.java:4844)
       at android.app.Activity.startIntentSenderForResult(Activity.java:4813)
       at com.google.android.play.core.appupdate.d.startIntentSenderForResult(d.java:9)
       at com.google.android.play.core.appupdate.b.a(b.java:35)
       at com.google.android.play.core.appupdate.b.a(b.java:5)
       at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.a(InAppUpdatePlugin.java:66)
       at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.a(InAppUpdatePlugin.java:2)
       at com.google.android.play.core.tasks.e.run(e.java:27)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

In our app we are using this code: 
```
@override
  Future<bool> launchUpdate() async {
    AppUpdateInfo info = await InAppUpdate.checkForUpdate();
    if (!info.immediateUpdateAllowed) return false;
    await InAppUpdate.performImmediateUpdate();
    return true;
  }
```

The bug happened with these devices: 
### Lenovo Tab M10 (FHD)
- Android: 9
- Root: No
- Portrait: Yes

### Samsung Galaxy S8
- Android: 9
- Root: No
- Portrait: Yes

**Comment by jonasbark** [comment]
Please check version 1.1.8.
