### ISSUE TITLE
Us

### ISSUE THREAD

**Issue by adityadroid** [feilfeilundfeil/flutter_in_app_update#30]
With the following piece of code:
```
  InAppUpdate.startFlexibleUpdate().then((_) {
// do something
              });
```
Is there a way to get a callback giving information as to the user chooses to update the app or presssed the "No Thanks" button?

![image](https://user-images.githubusercontent.com/17155247/81176775-43f8e080-8fc3-11ea-809d-05b786f7f53c.png)

Right now upon pressing "No Thanks" the following exception is thrown:
```
MissingPluginException: MissingPluginException(No implementation found for method startFlexibleUpdate on channel in_app_update)
  File "platform_channel.dart", line 319, in MethodChannel.invokeMethod
  File "<asynchronous suspension>"
  File "in_app_update.dart", line 33, in InAppUpdate.startFlexibleUpdate
  File "splash_page.dart", line 88, in _SplashPageState.checkForUpdates.<fn>
  File "zone.dart", line 1134, in _rootRunUnary
  File "zone.dart", line 1031, in _CustomZone.runUnary
  File "zone.dart", line 933, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 338, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 265, in _BufferingStreamSubscription._add
  File "stream_controller.dart", line 766, in _SyncStreamControllerDispatch._sendData
  File "stream_controller.dart", line 642, in _StreamController._add
  File "stream_controller.dart", line 588, in _StreamController.add
  File "zone.dart", line 1134, in _rootRunUnary
  File "zone.dart", line 1031, in _CustomZone.runUnary
  File "zone.dart", line 933, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 338, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 593, in _DelayedData.perform
  File "stream_impl.dart", line 709, in _StreamImplEvents.handleNext
  File "stream_impl.dart", line 669, in _PendingEvents.schedule.<fn>
  File "zone.dart", line 1122, in _rootRun
  File "zone.dart", line 1023, in _CustomZone.run
  File "zone.dart", line 925, in _CustomZone.runGuarded
  File "zone.dart", line 965, in _CustomZone.bindCallbackGuarded.<fn>
  File "zone.dart", line 1126, in _rootRun
  File "zone.dart", line 1023, in _CustomZone.run
  File "zone.dart", line 925, in _CustomZone.runGuarded
  File "zone.dart", line 965, in _CustomZone.bindCallbackGuarded.<fn>
  File "schedule_microtask.dart", line 43, in _microtaskLoop
  File "schedule_microtask.dart", line 52, in _startMicrotaskLoop
```

**Comment by rubenvereecken** [comment]
Just wanted to add my voice because I think it'd be really useful.

Perhaps even a callback for when the user opts out of a forced update, because that also just throws an exception:

```
2020-08-26 11:58:49.953 15777-15821/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Update failed, 0, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)
    <asynchronous suspension>
    #2      InAppUpdate.performImmediateUpdate (package:in_app_update/in_app_update.dart:22)
    <asynchronous suspension>
    #3      StartupScreenBloc.onSuccess (package:woushe_refactored/src/screens/startup_screen_bloc.dart:66)
    <asynchronous suspension>
```
