### ISSUE TITLE
[severe] App crache (InAppUpdatePlugin.kt line 89)

### ISSUE THREAD

**Issue by terryBaz** [feilfeilundfeil/flutter_in_app_update#31]
Hello,

My app is crashing on many devices (more than 34 devices), please find below the related informations:
 
- version `1.1.7`.

- my code : 
```dart
Future<void> checkForUpdate() async {
    InAppUpdate.checkForUpdate().then((info) {
      if (info?.updateAvailable == true && info?.flexibleUpdateAllowed == true)
        InAppUpdate.startFlexibleUpdate().then((_) {
          InAppUpdate.completeFlexibleUpdate().then((_) {
          }).catchError((e) => dd(e));
        }).catchError((e) => dd(e));
    }).catchError((e) => dd(e));
  }
```

- Crashlytics stacktrace:
```log
Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by android.content.IntentSender$SendIntentException
       at android.app.Activity.startIntentSenderForResultInner(Activity.java:4946)
       at android.app.Activity.startIntentSenderForResult(Activity.java:4915)
       at com.google.android.play.core.appupdate.d.startIntentSenderForResult(:9)
       at com.google.android.play.core.appupdate.b.startUpdateFlowForResult(:35)
       at com.google.android.play.core.appupdate.b.startUpdateFlowForResult(:5)
       at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.onSuccess(InAppUpdatePlugin.kt:89)
       at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.onSuccess(InAppUpdatePlugin.kt:21)
       at com.google.android.play.core.tasks.e.run(:27)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

- device info
![image](https://user-images.githubusercontent.com/29728203/81493632-4cdb0200-92a2-11ea-8ff1-fc6c31ef0730.png)

![image](https://user-images.githubusercontent.com/29728203/81493627-43519a00-92a2-11ea-849a-596b0468a445.png)

![image](https://user-images.githubusercontent.com/29728203/81493655-87dd3580-92a2-11ea-877f-736025632597.png)

- one example : 
Brand: samsung
Model: Galaxy A30
Orientation: Portrait
RAM free: 1.06 GB
Disk free: 25.55 GB
Operating System
Version: 9
Orientation: Portrait
Rooted: No

thanks :)

**Comment by terryBaz** [comment]
@jonasbark would you check this, it has *39 crashes affecting 34 users* in less than 24h -and numbers are up-
thank you.

**Comment by jonasbark** [comment]
Please check version 1.1.8.
