### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by canewsin** [feilfeilundfeil/flutter_in_app_update#42]
```
2020-09-20 10:33:41.199 21634-21634/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.canews.zeronet, PID: 21634
    java.lang.IllegalArgumentException: kotlin.Unit
        at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.onSuccess(InAppUpdatePlugin.kt:148)
        at de.ffuf.in_app_update.InAppUpdatePlugin$onActivityResumed$1.onSuccess(InAppUpdatePlugin.kt:29)
        at com.google.android.play.core.tasks.e.run(Unknown Source:27)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by canewsin** [comment]
Happens on clicking update -> Google Play Shows Dialog -> when i click download app crashes.

**Comment by canewsin** [comment]
@jonasbark

**Comment by jonasbark** [comment]
Can you try the fix_42 branch?

**Comment by canewsin** [comment]
This puts update screen front instead of background update like an immediate update, i read in docs that flexible update doesn't interrupt app usage flow and makes update in the background.

**Comment by canewsin** [comment]
@jonasbark

**Comment by canewsin** [comment]
@jonasbark are you working on this ?

**Comment by jonasbark** [comment]
No, I'm not working on this ATM but feel free to add a PR to support this case

**Comment by zjamshidi** [comment]
My app's users are facing the same issue.

**Comment by zjamshidi** [comment]
OH. you made a new build.
