### ISSUE TITLE
Application crashed when update was cancelled or when update was not available.

### ISSUE THREAD

**Issue by hassan123123** [feilfeilundfeil/flutter_in_app_update#61]
Application crashed when no update was available or if update was cancelled.

Exception handling doesn't work either, I even tried try - catch blocks.

Here is the logs:
I/PlayCore(24065): UID: [10955]  PID: [24065] AppUpdateService : Initiate binding to the service.
I/PlayCore(24065): UID: [10955]  PID: [24065] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore(24065): UID: [10955]  PID: [24065] AppUpdateService : linkToDeath
I/PlayCore(24065): UID: [10955]  PID: [24065] OnRequestInstallCallback : onRequestInfo
I/PlayCore(24065): UID: [10955]  PID: [24065] AppUpdateService : Unbind from service.
D/AndroidRuntime(24065): Shutting down VM
I/flutter (24065): PlatformException(Update failed, 0, null, null)
E/AndroidRuntime(24065): FATAL EXCEPTION: main
E/AndroidRuntime(24065): Process: com.frynds.hungry, PID: 24065
E/AndroidRuntime(24065): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1276, result=0, data=null} to activity {com.frynds.hungry/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(24065): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4962)
E/AndroidRuntime(24065): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003)
E/AndroidRuntime(24065): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(24065): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(24065): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(24065): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
E/AndroidRuntime(24065): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(24065): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(24065): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(24065): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24065): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(24065): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(24065): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(24065): 	at com.paytm.allinonesdk.AllInOneSdkPlugin.onActivityResult(Unknown Source:2)
E/AndroidRuntime(24065): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime(24065): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(24065): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
E/AndroidRuntime(24065): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:624)
E/AndroidRuntime(24065): 	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
E/AndroidRuntime(24065): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4955)
E/AndroidRuntime(24065): 	... 11 more
I/Process (24065): Sending signal. PID: 24065 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by hassan123123** [comment]
My Mistake
