### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by tbarbette** [feilfeilundfeil/flutter_in_app_update#68]
Hi!
The in_app_update does not work.

```
E/MethodChannel#in_app_update(29957): java.lang.IllegalArgumentException: kotlin.Unit
E/MethodChannel#in_app_update(29957): 	at de.ffuf.in_app_update.InAppUpdatePlugin.checkAppState(InAppUpdatePlugin.kt:156)
E/MethodChannel#in_app_update(29957): 	at de.ffuf.in_app_update.InAppUpdatePlugin.startFlexibleUpdate(InAppUpdatePlugin.kt:168)
E/MethodChannel#in_app_update(29957): 	at de.ffuf.in_app_update.InAppUpdatePlugin.onMethodCall(InAppUpdatePlugin.kt:62)
E/MethodChannel#in_app_update(29957): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#in_app_update(29957): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#in_app_update(29957): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#in_app_update(29957): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#in_app_update(29957): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#in_app_update(29957): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#in_app_update(29957): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
E/MethodChannel#in_app_update(29957): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#in_app_update(29957): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#in_app_update(29957): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E/DartMessenger(29957): Uncaught exception in binary message listener
E/DartMessenger(29957): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(29957): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/DartMessenger(29957): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
E/DartMessenger(29957): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(29957): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/DartMessenger(29957): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(29957): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/DartMessenger(29957): 	at android.os.Looper.loop(Looper.java:181)
E/DartMessenger(29957): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
E/DartMessenger(29957): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(29957): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/DartMessenger(29957): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

```

My usage is pretty standard though:
```
    WidgetsBinding.instance.addPostFrameCallback((_) {
      InAppUpdate.startFlexibleUpdate().then((_) {
        print("Starting flexible update");
        InAppUpdate.completeFlexibleUpdate().then((_) {
          print("Updated!");
        }).catchError((e) {
          print("When updating");
          print(e);
        });
      }).catchError((e) {
        print("When checking update");
        print(e);
      });
    });
```

**Comment by carlos-labrador** [comment]
it does not work in debug mode , you should read this: [Test in-app updates](https://developer.android.com/guide/playcore/in-app-updates/test)

**Comment by tbarbette** [comment]
That's in release mode and installed from the play store, that's why I have the logcat only. Not sure how to get more info...

**Comment by tbarbette** [comment]
I guess some recent flutter update broke the plugin? I'm on the latest everything as my project is new.

**Comment by cmalex23** [comment]
This is most likely because you didn't call `checkForUpdate` before.

**Comment by tbarbette** [comment]
Yes, it seems it was the issue. Maybe this could be checked internally to at fail more gracefully? The update API does not need the "info" so it's not very clear it is needed.
