### ISSUE TITLE
PlatformException(Update failed, 0, null, null) StandardMethodCodec.decodeEnvelope

### ISSUE THREAD

**Issue by dagba** [feilfeilundfeil/flutter_in_app_update#73]
Using 1.1.15 version
App closes while installing an update
Producing bug:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Update failed, 0, null, null)
       at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:582)
       at MethodChannel._invokeMethod(MethodChannel.java:159)
       at InAppUpdate.performImmediateUpdate(InAppUpdate.java:22)
       at .suspension>(.java)
```
code:
```
  @override
  void startUpdateFlow({
    @required AppVersionState scenario,
  }) {
    InAppUpdate.checkForUpdate().then((storeUpdateInfo) {
      if (scenario == AppVersionState.hard && storeUpdateInfo.updateAvailable) {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (context) => UpdateRequiredScreen(
              onTap: () {
                try {
                  InAppUpdate.performImmediateUpdate();
                } catch (e) {
                  DxRouter.instance.openStorePage();
                }
              },
            ),
          ),
        );
        return;
      }

      if (storeUpdateInfo.updateAvailable) {
        InAppUpdate.startFlexibleUpdate().then((_) {
          InAppUpdate.completeFlexibleUpdate();
        });
      }
    });
  }
}
```

**Comment by Ghoral** [comment]
found any solution ?

**Comment by dagba** [comment]
@Ghoral no(

**Comment by Ghoral** [comment]
I read somewhere that it works on playstore, and has problem only on debug mode.

**Comment by jonasbark** [comment]
Yes - it's definitely caused by your configuration. Please check the Readme and the attached links.
